lib/honeycomb/span.rb
@martin308 sorry, I don't have write access to this repo and this is the only way I could think of to suggest the change.
=> Expose event to #span block

.gitignore, CONTRIBUTORS.md, lib/honeycomb/integrations/faraday.rb, spec/honeycomb/integrations/faraday_spec.rb
https://github.com/honeycombio/beeline-ruby/issues/25
=> No-op if no client found in Faraday integration

.travis.yml, Appraisals, README.md, gemfiles/rails_6.gemfile
Rails 6 has been released now so we should test against that instead of rc2
=> Update to release version of rails 6

README.md
=> Include note about tested versions of rails

lib/honeycomb-beeline.rb
I didn't push my fix for the spelling of integration before I merged #35, here is the commit
=> Fix integration spelling

Gemfile.lock, honeycomb-beeline.gemspec
Updating rake as per CVE-2020-8130
=> Only change Gemfile.lock

.circleci/config.yml
Just noticed this on the circle ci blog. Makes the build config a lot simpler and way easier to update with new configs!
=> matrix builds are finally here!

.circleci/config.yml
Now that we have an actual build matrix it's much easier to add new versions!
=> Add ruby 2.7 to the matrix

Gemfile.lock, README.md, honeycomb-beeline.gemspec, spec/spec_helper.rb
Add codecov to track test code coverage
=> Add codecov

README.md
Title says it all! I kept it short and sweet, just wanted to include a mention of the Appraisal gem for testing.
=> [docs] Add testing info to readme

.circleci/config.yml
This brings us up to speed with our current guidelines for public repos
=> Add GitHub publish step

UPGRADING.md
=> Add upgrade notes for major version bump

CHANGELOG.md, Gemfile.lock, lib/honeycomb/beeline/version.rb
also add changelog, and backfill old release notes
=> Prepare for a minor bump release

.circleci/config.yml
=> fix build artifacts step to use the beeline gemspec

spec/honeycomb/integrations/rails_spec.rb
* adding back test coverage introduced in https://github.com/honeycombio/beeline-ruby/pull/123
* #123 was reverted so we can continue to release a non-major version off main
=> Add test case for 5xx response

CHANGELOG.md, lib/honeycomb/beeline/version.rb
- Bump the version and update the changelog for release.
=> Prepare v2.8.0

CHANGELOG.md, lib/honeycomb/beeline/version.rb
=> prepare 2.8.1 release

CHANGELOG.md, lib/honeycomb/beeline/version.rb
Prepares the v2.8.2 release.
- Add chanelog entry
- Update version to 2.8.2
=> Prepare 2.8.2 release

CHANGELOG.md, lib/honeycomb/beeline/version.rb
- preps v2.9.0 release
- update version
- update changelog
=> prep v2.9.0 release

CHANGELOG.md, lib/honeycomb/beeline/version.rb
Prepares the v2.10.0 release.
- Adds changelog
- Updates library version to 2.10.0
=> Prepare v2.10.0 release

CHANGELOG.md, lib/honeycomb/beeline/version.rb
Prepares the v2.11.0 release.
- Updates version to 2.11.0
- Adds changelog entry
=> Prepare 2.11.0 release

CHANGELOG.md, README.md, lib/honeycomb/beeline/version.rb
Prepares the v3.0.0 release.
- Update version to 3.0.0 lib/honeycomb/beeline/version
- Add changelog entry
=> rel: Prepare v3.0.0 release
