.gitignore
Rakefile
honeycomb-beeline.gemspec
spec/instrumented_apps/rails_activerecord/app.rb
spec/instrumented_apps/rails_activerecord/app_spec.rb
spec/instrumented_apps/sinatra_activerecord/app.rb
spec/support/db_active_record.rb
spec/support/fake_auth.rb

The Beeline itself doesn't actually need any changes to support Rails, so this PR serves mainly as instructions for tying together the changes needed to the instrumentation repos: https://github.com/honeycombio/rack-honeycomb/pull/8 and https://github.com/honeycombio/activerecord-honeycomb/pull/2. This PR also adds integration tests to verify that the Beeline's auto-install works correctly for a Rails/ActiveRecord app.
The CI build for this PR will not currently pass, because the Rails integration tests depend on the aforementioned PRs to rack-honeycomb and activerecord-honeycomb. So recommended steps to merge and release Rails support:
1. merge https://github.com/honeycombio/rack-honeycomb/pull/8 and publish a new release of rack-honeycomb (say, rack-honeycomb 0.3.0)
2. merge …

Rails support

---

honeycomb-beeline.gemspec
lib/honeycomb/client.rb
lib/honeycomb/span.rb
spec/beeline/span_spec.rb
spec/instrumented_apps/rails_activerecord/app.rb
spec/instrumented_apps/rails_activerecord/app_spec.rb
spec/instrumented_apps/sinatra_activerecord/app.rb
spec/instrumented_apps/sinatra_activerecord/app_spec.rb
spec/instrumented_apps/sinatra_sequel/app.rb
spec/support/test_logger.rb

This cleans up the "secret" (although technically public) tracing API into something that should be reasonably usable by customers and we should be able to bless as a public API. It also adds support for encoding and decoding the trace context serialisation format specified [in the Node Beeline source](https://github.com/honeycombio/beeline-nodejs/blob/6fe61aafce61c8106a1c9dacbe2f99210e3698ae/lib/propagation.js#L12-L25).
With this PR, plus https://github.com/honeycombio/rack-honeycomb/pull/9, https://github.com/honeycombio/activerecord-honeycomb/pull/3 and https://github.com/honeycombio/faraday-honeycomb/pull/1, we can support cross-process tracing for Rails apps (e.g. the above screenshot shows a Rails app making an HTTP request to a Sinatra "auth" app).
The new API is (mostly) not …

Tracing API and cross-process tracing

---

honeycomb-beeline.gemspec

Latest version of sinatra breaks older ruby version compatibility

Use supported version of sinatra

---

honeycomb-beeline.gemspec
lib/honeycomb/instrumentations.rb
spec/instrumented_apps/sinatra_sequel/app.rb

There is an issue with the way we have constructed the `Sequel` instrumentation that is problematic when included with applications that don't use `Sequel` but do have other gems that can support `Sequel`. 
In this scenario the other gems believe that `Sequel` is in use and attempt to configure themselves with `Sequel` which will fail as it is only present in the beeline.
This removes the default inclusion of the https://github.com/honeycombio/sequel-honeycomb gem which will fix the above issue. For people using the `Sequel` instrumentation there will be a couple of additional steps to take to instrument their `Sequel` calls. See the tests for an example of this

Remove default inclusion of Sequel instrumentation

---

UPGRADING.md

Start an upgrading guide to document upgrading between versions with breaking changes. Kick it off with a guide to upgrading to this gem from the now deprecated [`honeycomb-rails` gem](https://github.com/honeycombio/honeycomb-rails)

Add UPGRADING guide

---

.travis.yml
Appraisals
gemfiles/rails_6rc2.gemfile

Rails6 rc2 has been released! Update our testing matrix to use rc2 instead of rc1.

Update to test against rails6 rc2

---

lib/honeycomb/span.rb
spec/honeycomb/span_spec.rb

I have an application which has a health check endpoint, which I'd like to filter out from Honeycomb. The endpoint gets a lot of requests and they aren't particularly interesting to log.
While trying to set a sample_hook, I noticed that child spans created by the ActiveSupport subscriber integration aren't being filtered out. Since every request to this healthcheck endpoint was generating a child span via ActionController, the sample hook was only able to filter out half of the spans. 
This PR sets the `sample_hook` parameter when creating child spans, so that any span can potentially be filtered out.
Let me know if there's a better way to accomplish this. I noticed that [`send_children`](https://github.com/honeycombio/beeline-ruby/blob/master/lib/honeycomb/span.rb#L101) is called in …

Set sample hook on child spans

---

lib/honeycomb-beeline.rb
lib/honeycomb/integrations/rails.rb
lib/honeycomb/integrations/railtie.rb

Splits up the rails and railtie integrations so that people can skip loading the railtie if they want more control over where the middleware is added in the stack.
@sethjohnson-flexe this should allow you to run your app without the railtie being loaded so that you can add the middleware in a suitable location. How do you feel about this solution?
It would look something like the below, you would then need to add the middleware manually in a location that works with your application.
`HONEYCOMB_INTEGRATIONS=rails,faraday bundle exec rails server`

Split rails and railtie integrations

---

lib/honeycomb/integrations/rails.rb

Fixes https://github.com/honeycombio/beeline-ruby/issues/31.
Tracing this through, we call this [method](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/parameters.rb#L50) and `action_dispatch.request.parameters` is nil. So we fall into this [method](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/request.rb#L381) which eventually ends up calling this [lambda](https://github.com/rails/rails/blob/a3d54d2afe557b243d6b18f9adf119f60ffb8242/actionpack/lib/action_dispatch/http/parameters.rb#L11) which raises an error when `raw_post` is nil. 
I'm not entirely clear what [twirp](https://github.com/twitchtv/twirp-ruby) is doing to the request to end up in this state and have struggled to reproduce this in a test. This should prevent the …

Skip params when unavailable

---

lib/honeycomb/integrations/railtie.rb

Try inserting middleware after ActionDispatch::ShowExceptions

---

lib/honeycomb-beeline.rb
lib/honeycomb/client.rb

Expose the current trace and current span in the top level scope. These properties are useful for doing custom instrumentation.

Expose context methods for current trace and span

---

lib/honeycomb/client.rb
spec/honeycomb/client_spec.rb

These mistakenly have 'request' in them when it can be used in a non
request context. It also better matches the other beelines.

Fix bad request based key names

---

lib/honeycomb/integrations/redis.rb
spec/honeycomb/integrations/redis_spec.rb

The idea of this attribute was that you'd be able to turn off the Redis
instrumentation by blanking out the Honeycomb client.
However, by using `||`, the code was *actually* falling back to the
global `Honeycomb.client` whenever we set `Redis.honeycomb_client =
nil`. The spec was passing erroneously because it was being run in a
context where `Honeycomb.client` was *also* `nil`. Oops!
By switching this to use the `defined?` check, we'll return `nil` from
`Redis.honeycomb_client` as long as it's been explicitly blanked out by
the user.

Fix `Redis.honeycomb_client = nil`

---

lib/honeycomb/integrations/rails.rb
spec/honeycomb/integrations/rails_spec.rb

Handle bad request params

---

lib/honeycomb-beeline.rb
lib/honeycomb/client.rb
spec/honeycomb/beeline_spec.rb

There are cases where a beeline user would like to get access to the
libhoney instance directly. This makes it possible by calling
`Honeycomb.libhoney` at any time.

Make the libhoney client instance accessible.

---

lib/honeycomb/integrations/rails.rb
spec/honeycomb/integrations/rails_spec.rb

This refactoring avoids ever parsing GET/POST parameters to obtain the
Rails routing information required for the `request.action`,
`request.controller`, and `request.route` fields.
This is accomplished in two ways:
1. Use `ActionDispatch::Request#path_parameters` instead of
`ActionDispatch::Request#params`. The former is the subset of data we
need for `request.action` + `request.controller`, and in fact are the
values merged into the latter hash after `#params` parses the normal
GET/POST parameters. So we can avoid the extraneous parsing by just
getting the path parameters straight from the horse's mouth.
2. Call `ActionDispatch::Journey::Router#recognize` on a simplified
request that *only* contains the necessary routing information. The
`#recognize` method will yield the …

Rework the Rails integration

---

Gemfile.lock
honeycomb-beeline.gemspec

Updating to address security vulnerability flagged by Github (CVE-2020-8130)

Update rake version (CVE-2020-8130)

---

Gemfile.lock
honeycomb-beeline.gemspec
lib/honeycomb/integrations/active_support.rb
spec/honeycomb/integrations/active_support_spec.rb

Don't prematurely call to_s on hashes, as we can actually serialize them in a way we can parse.
This enables us to construct nested JSON in libhoney, serializing things so they can be later unpacked on Honeycomb's side.

Serializes ActionController::Parameters correctly

---

spec/honeycomb/integrations/aws_spec.rb

We have intermittent test failures with the AWS tests. This should hopefully fix them although ideally we should not be relying on sample to obtain a client as this is not very deterministic.
In order to reproduce this I ran the following under both the aws-2 and was-3 appraisal profiles
`bundle exec appraisal aws-2 bundle console`
```
Aws.config.update(stub_responses: true)
clients = Aws::Partitions.service_ids.keys.map {|service| Aws.const_get(service).const_get(:Client)}
clients.map do |c|
begin
c.new
rescue => e
@err = e
ensure
puts "#{@err} #{c}" if @err
@err = nil
end
end
```
`bundle exec appraisal aws-3 bundle console`
```
Aws.config.update(stub_responses: true)
clients = Aws::Partitions.service_ids.keys.map {|service| Aws.const_get(service).const_get(:Client)}
clients.map do |c| …
```

Include endpoint argument to all clients

---

lib/honeycomb/configuration.rb

In Ruby 2.7 passing the last argument as an options hash if the receiver uses keyword arguments is no longer allowed and emits a deprecation warning.
This PR applies the recommended fix of adding ** to covert the options hash into the correct keyword arg format.
There may be more deprecation warnings to fix in other parts of the codebase but these were the ones that jumped out to me right away.

Properly pass options for Ruby 2.7

---

.circleci/config.yml

Adds a workflow that runs once a day to lint and test whatever is on master. Followed these docs, no idea if it works or not https://circleci.com/docs/2.0/triggers/
It would be nice to stay on top of build failures like this https://github.com/honeycombio/beeline-ruby/pull/86 rather than have people submit PRs that fail to build because of some dependency failing.

Trigger a nightly build

---

.rubocop.yml
lib/honeycomb/span.rb
spec/honeycomb/span_spec.rb

Resolves #84.
The spec changes look really bad, but the main change is to dump the existing specs into another `describe` block and add an additional spec to check that after the child is sent it won't try to send any sent children. Might be easiest to just look at the last two commits as the shuffling around is isolated to the first commit.

remove children after sending

---

.circleci/config.yml
Gemfile.lock
honeycomb-beeline.gemspec

We claim to support ruby 2.2 in the `gemspec` yet we don't run any of our tests on this version of ruby.
Adds 2.2 to the matrix and excludes framework versions that don't run on 2.2

Add ruby 2.2 to the test matrix

---

lib/honeycomb/client.rb
spec/honeycomb/client_spec.rb

Updates the Client#start_span method to store a reference to the current span, rather than repeatedly referencing `context.current_span`.
The method `Span#send` is a public method, which means that it is possible for instrumentation to send the span from within a block passed to `Client#start_span`. Under those circumstances, one of two problematic scenarios can occur:
1) If the current span is _not_ the root span, then start_span will end up sending the parent span instead of the child span.
2) If the current span _is_ the root span, then start_span will raise `ArgumentError: no method name given`. This is due to the fact that `context.current_span` returns `nil` and `NilClass#send` expects a parameter, i.e. the method name to send.
By storing a reference to the current span, we can …

fix(client): reference current span in start_span

---

spec/honeycomb/deterministic_sampler_spec.rb

This should do the trick for the bounds that is occasionally not met in tests.
For sample_rate of 10, we've been using a margin of 0.05, which tests for `samples` to be within 250.00 of the 5000 `expected`. It's occasionally a few outside of that, leading to very occasional build failure.
Bumping to 0.06 will increase the bounds enough that we're still checking sufficiently without running into this break. (5000 * 0.06 == 300)

fix: increase margin for sampling distribution test

---

spec/honeycomb/integrations/aws_spec.rb

In a minor version bump of the AWS Dynamo gem the error_detail field is now populated causing these tests to break. Fix by being more lenient in expected output from AWS gem.

Fix AWS3 gem tests

---

spec/spec_helper.rb

Allows for marking spec functions with `:focus` to assist with debugging.

Add rspec filter :focus for assisting with debugging tests

---

lib/honeycomb-beeline.rb
lib/honeycomb/client.rb
spec/honeycomb/beeline_spec.rb

The return value of `Honeycomb.add_field` (and similarly
`Honeycomb.add_field_to_trace`) is the `Libhoney::Event` object that had
the field added.
However, I'd often have the pattern in my code of using
```ruby
def something
(some || sort && of ** expression).tap do |value|
Honeycomb.add_field('field', value)
end
end
```
That is, I still want the return value of the `#something` method, but I
wanted to track its value in a Honeycomb field. The methods added in
this commit allow the more natural pattern of wrapping the computation
in a block like so:
```ruby
def something
Honeycomb.with_field('field') do
some || sort && of ** expression
end
end
```
It's just a minor feature, but one that would make some of my code a
little nicer looking. Especially with predicates, where I currently have …

Add Honeycomb.{with_field,with_trace_field}

---

lib/honeycomb/integrations/railtie.rb
spec/honeycomb/integrations/rails_spec.rb

Reverts honeycombio/beeline-ruby#123
After discussing with team, we feel this change in its current form necessitates a major version bump due to `error` and `error_details` going missing on 4xx and 5xx requests. Going to pull it out of `main` so we can continue the release train, and open a new PR for this change so we can attempt to make it backwards-compatible or merge into a 3.x.x branch.

Revert "Move Middleware to be before ActionDispatch::ShowExceptions"

---

lib/honeycomb/integrations/redis.rb
spec/honeycomb/integrations/redis_spec.rb

The honeycomb-beeline Redis integration attempts to [sanitize fields][1] to remove sensitive data. Unfortunately, it expects the fields to be symbol keys. For people who create their own Redis connections, it is probably likely that this is an issue; as the Redis docs use symbol names. However, the Redis lib is flexible enough to support string keys. Additionally, the Rails' Action Cable Redis configuration uses a "hash with indifferent access" which internally utilizes string keys.
This adds option key normalization to support both symbol and string keys for field filtering. The choice to convert to `to_sym` instead of `to_s` was based on some basic benchmarking of the two. Further, benchmarking comparing a guard clause with safe navigation was also performed (NOTE: this lib still …

Updates Redis event-field filter to handle string keys in options in addition to symbol keys.

---

spec/honeycomb/integrations/rails_spec.rb

With #153 merged, this addresses the TODO comments left from adding tests for the events generated from error responses in #132.
Also adds a few more tests for the `error` and `error_details` fields that are the candy-like center of this effort to capture the details of errors in Rails.

make Rails spec consistent with Honeycomb Railtie initialization

---

lib/honeycomb/integrations/redis.rb
spec/honeycomb/integrations/redis_spec.rb

Fixes #57.
There was a major performance bottleneck in the Redis integration when prettifying the `redis.command` field. The original implementation would scan the string character-by-character and manually push possibly-escaped results to another string. This implementation replaces that manual logic with some strategic uses of `String#encode!` and `String#gsub!`.
There's a minor regression in the behavior with the interaction between invalid UTF-8 bytes and basic backslash escaping, but I think the payoff is well worth it. I added tests to codify this new behavior.
Using this benchmark:
```ruby
require "bundler/inline"
gemfile do
gem "honeycomb-beeline", path: "~/repos/beeline-ruby"
gem "redis", source: "https://rubygems.org"
end
require "benchmark"
require "net/http"
html = …
```

Improve performance of Redis command serialization

---

CHANGELOG.md
Gemfile.lock
lib/honeycomb/beeline/version.rb

Updates library version to `2.5.0` and adds changelog entry.

Prepare 2.5.0 release

---

.circleci/config.yml
Appraisals
README.md
gemfiles/aws_2.gemfile
lib/honeycomb/integrations/faraday.rb
lib/honeycomb/integrations/rack.rb

- The absence of testing the latest version of Ruby.
- Easiest to walk the commits, starting with [the first](https://github.com/honeycombio/beeline-ruby/pull/171/commits/e5fb055ef74fecc1e2a06356791007d19744e533). Each commit message describes a discrete fix for adding Ruby 3.0 to the matrix.

add Ruby 3.0 to CI matrix

---

spec/honeycomb/integrations/redis_spec.rb

- redis gem update includes additional READONLY commands being executed in cluster mode, which results in additional events generated by the beeline
- fixes #177 
- decided to keep the tests specific and create a new IF branch for the newer versions of the gem

fix: new redis gem version broke tests

---

.rubocop.yml
lib/honeycomb/configuration.rb
lib/honeycomb/propagation/default.rb
spec/honeycomb/propagation/default_spec.rb

Closes https://github.com/honeycombio/beeline-ruby/issues/180
This is a very simple replacement incoming trace parent propagator hook. It will by default process either a Honeycomb or a W3C trace propagation header. If both are present, which we expect will be a very unusual case, the hook will prefer the Honeycomb trace header.

feat: accept both w3c and honeycomb propagation headers by default

---

honeycomb-beeline.gemspec

- Fixes #186 
- 0.5.0 introduced a change that doesn't work in Ruby 2.2. 0.5.1 reverted that change and subsequent releases will include a minimum Ruby version of 2.3. This version constraint should carry us while we've got our current broad Ruby version test matrix.

[dev] set minimum version of rspec_junit_formatter

---

lib/honeycomb/configuration.rb
spec/honeycomb/configuration_spec.rb

- Fixes #187 
Use the Libhoney's public API for setting a user-agent-addition during client instantiation. This leaves in place the existing behavior—[a race to munge a private instance variable between client instantiation and sending the first event](https://github.com/honeycombio/beeline-ruby/blob/v2.8.0/lib/honeycomb/client.rb#L19-L23)—to keep the Beeline adding its version info to Libhoney versions prior to v1.19.0. I expect we'll remove that munging in a future major version bump that moves the libhoney dependency to v2.0+ and drops support for older Rubies.

fix Beeline user-agent addition when creating a Libhoney client

---

honeycomb-beeline.gemspec

We have a pessimistic version guard on libhoney that prevents us from using 2.x. We should remove it.
- Removes dependency guard of libhoney

Remove the upperbound on libhoney version

---

.circleci/config.yml
.rubocop.yml
lib/generators/honeycomb/honeycomb_generator.rb
lib/honeycomb/client.rb
lib/honeycomb/configuration.rb
lib/honeycomb/context.rb
lib/honeycomb/propagation/default_modern.rb
lib/honeycomb/propagation/honeycomb_modern.rb
lib/honeycomb/propagation/w3c.rb
lib/honeycomb/trace.rb
spec/generators/honeycomb/honeycomb_generator_spec.rb
spec/honeycomb/beeline_spec.rb
spec/honeycomb/client_spec.rb
spec/honeycomb/configuration_spec.rb
spec/honeycomb/integrations/aws_spec.rb
spec/honeycomb/propagation/default_modern_spec.rb
spec/honeycomb/propagation/honeycomb_modern_spec.rb
spec/honeycomb/trace_spec.rb

- closes #193 
If using an environment-aware key:
- dataset = serviceName
- add field of `service.name` in addition to `service_name` to be more consistent with otel
- use default service name of `unknown_service:<processname>` or `unknown_service:ruby` if process name is unavailable and no service name provided
- don't propagate dataset by default unless legacy key (to prevent overwriting of service name)
- warn on missing service name and api key
- warn on presence of dataset, noting data will be sent to service name
- if dataset derived from service name starts with `unknown_service*`, truncate to `unknown_service` for dataset
- if dataset derived from service name has extra whitespace, trim whitespace and console warn on diff
warning provided if dataset is set in config when using …

Add Environment and Services support

---

lib/honeycomb/span.rb
spec/honeycomb/client_spec.rb

A regression was introduced by #98 in computing the `meta.span_type` field.
The field's value is given by the `Honeycomb::Span#span_type` method: https://github.com/honeycombio/beeline-ruby/blob/8b36cd0c94aba9378b6b0d74c9b593fc3f2bac0e/lib/honeycomb/span.rb#L180-L188
This field gets added as the span is being sent: https://github.com/honeycombio/beeline-ruby/blob/8b36cd0c94aba9378b6b0d74c9b593fc3f2bac0e/lib/honeycomb/span.rb#L159
For "mid" spans, this amounts to checking the `Honeycomb::Span#children` array at send-time. Prior to #98, this array would be full all the time, as no values were ever removed. However, #98 added this line at the end of `#send_internal`: https://github.com/honeycombio/beeline-ruby/blob/8b36cd0c94aba9378b6b0d74c9b593fc3f2bac0e/lib/honeycomb/span.rb#L152
So if all …

Fix regression with mid vs leaf meta.span_type detection

---

lib/honeycomb/integrations/rack.rb
spec/honeycomb/integrations/rack_spec.rb
spec/honeycomb/integrations/rails_spec.rb
spec/support/event_data_shared_examples.rb

This will be helpful to determine where requests are coming from in our application. 
Co-Authored-by: Marcelo Guindon <marcelo@modeanalytics.com>

Add HTTP referer to rack integration

---

bin/console

- The `bin/console` script not working
- The `honeycomb/beeline` does not exist and this script does not work. Instead load the relative file from the source tree.

Console: Load the file that exists

---

examples/rails52/Dockerfile
examples/rails52/Gemfile

- puma: quiets a dependabot alert originating in the example; not a security problem for users of this library
- ruby: 2.5 was ollllld

Update Ruby and puma in the example

---

.rubocop.yml
lib/honeycomb-beeline.rb
lib/honeycomb/integrations/rake.rb
spec/honeycomb/integrations/rake_spec.rb
spec/support/test_tasks.rake

When running a Rake task, the Honeycomb integration typically creates the root node of the trace (since the task is the entry point into the program). For short-lived tasks like `rake db:migrate`, this works great. However, tasks might be long-lived. For example, `rake resque:work` [runs forever](https://github.com/resque/resque/blob/e068909cc0cbf1afa2fa4cb33be2809a397ce9d3/README.markdown#running-workers), dequeueing background jobs on a loop. Ideally, we'd like a separate trace for each job that gets dequeued. But with the Rake integration enabled, all the jobs' traces point back up at the auto-generated root span, which will be missing until the worker process finally dies. This has been discussed before in Pollinators: https://honeycombpollinators.slack.com/archives/CJR134U2F/p16439891 …

Let Rake spans be disabled programmatically

---

honeycomb-beeline.gemspec

- nightly builds are [failing](https://app.circleci.com/pipelines/github/honeycombio/beeline-ruby?branch=main)
- webmock requires ruby 2.3+ since version 3.15

maint: fix nightly build

---

.circleci/config.yml

- ruby 3.1 was released in December 💎 
- we're currently testing ruby versions 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0
- deprecated `circleci/ruby` does not have an image for 3.1
- new `cimg/ruby` does not have images for 2.2 or 2.3
- 2.4 2.5 and 2.6 images from `cimg/ruby` have a default bundler gem (not the case in deprecated images), and we need a specific (different) version of bundler to test against rails 4.1 and 4.2
- split test in 2: test newer versions (2.7+) with new images and test-older-versions with deprecated images
- update default image to 2.7 since 2.6 is EOL

maint: add ruby 3.1 to CI matrix

---

honeycomb-beeline.gemspec

[v0.60.0](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md#0600-2018-10-26) includes a fix (6331) for false positives on Regexes assigned to a constant that will quiet the lint error that's appeared in nightly.
Less than v0.69.0 remains for Ruby 2.2 until a time that we decide to overhaul and update dev/test.

fix: set min rubocop to avoid false positive lint error

---

.circleci/config.yml
.circleci/setup-rubygems.sh

- use circle context for publishing ruby gem
- use `RUBYGEMS_API_KEY` instead of `GEM_HOST_API_KEY`

ci: use context for publishing ruby gem

---

.github/CODEOWNERS
honeycomb-beeline.gemspec
lib/honeycomb/beeline/version.rb

- update author from Martin to Honeycomb
- remove @martin308 from codeowners
- also [confirmed](https://rubygems.org/gems/honeycomb-beeline/versions/2.11.1.pre.dev) with a dev tag that the publish pipeline works for the honeycombio user in rubygems

maint: update author to honeycomb

---

spec/honeycomb/integrations/aws_spec.rb

- The AWS gem/API starting returning a new field, `x_amz_request_charged`. A new field made the spec matcher freak out in the nightly.
- Swap out `match()` for `include()` in the AWS specs
- Match is strict and expects *only* what it has been told.
- Include is fine with new key/values appearing so long as the existing ones are as expected.

ci: AWS specs updated to use include() instead of match()

---

.rubocop.yml
lib/honeycomb/propagation/default_modern.rb
lib/honeycomb/propagation/honeycomb.rb
lib/honeycomb/propagation/honeycomb_modern.rb
spec/honeycomb/propagation/honeycomb_modern_spec.rb
spec/honeycomb/propagation/honeycomb_spec.rb

- Resolves #231 
* Tests added to cover invalid UTF8 characters in trace field values for classic and E&S modes of Honeycomb propagation
* Replace invalid UTF8 characters when serializing in Honeycomb-flavored propagators
Mixes in the data cleaning logic already present in Libhoney::Cleaner to prepare trace data for JSON serialization.
* Refactor the encoding logic for serialization in an extracted method to avoid having the two implementations diverge.
* Decode trace context with the decoder that matches the encoder.
Testing revealed that decoding trace context would fail to produce a string parseable as JSON if some UTF8 characters were included in the data, even if those characters are valid. Because we encode with urlsafe, we need to decode with urlsafe.
* Disable the …

fix: clean invalid UTF8 from trace field values when generating propagation header

---

.gitignore
DEVELOPING.md
examples/rails52/Gemfile
examples/rails52/docker-compose.yml

- lack of notes on local development
- dependabot alert on example app (example dep, not a security problem for users of this library)
- Add basic `DEVELOPING.md` for when occasional maintenance is necessary
- Replace the `datadog/squid` image in the rails52 example with `ubuntu/squid` because the former has been removed from docker
- Add `Gemfile.lock` to the `.gitignore` file - we already intentionally don't check it in, so this just makes it less likely to inadvertently check it in
- Update puma in rails52 example to quiet dependabot alert

maint: add local dev notes and fix example

---

CHANGELOG.md
RELEASING.md
lib/honeycomb/beeline/version.rb

- new release
- update version
- update changelog
- update releasing doc for extra clarity (found to be helpful in other repos)

rel: prep v3.0.1

---

honeycomb-beeline.gemspec
lib/honeycomb/client.rb
lib/honeycomb/configuration.rb
spec/honeycomb/configuration_spec.rb

- Supporting ingest keys in classic environments
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206669928045914

feat: support classic ingest keys

---

spec/honeycomb/integrations/aws_spec.rb

- Tests on main were breaking in the weekly builds.
- aws-sdk-s3 v3.149.0 removed the `Aws::S3::BUCKET_REGIONS` constant[1] we were using, so switch up to using the accessor method `Aws::S3.bucket_region_cache`.
- aws-sdk-s3 v1.152.3 changed the regex for matching error response bodies[2], so update our stubbed error to keep up.
[1] https://github.com/aws/aws-sdk-ruby/commit/9d55e1f22e7f04ffc598adee949e993a31755cdb#diff-8232dab0dd0010d16882beee85916c9ec1d9b1573e87fb72f29d6530e2951e9cL78
[2] https://github.com/aws/aws-sdk-ruby/commit/49f47130237ba27f43c2c46aa06c3e0620a6086f#diff-38231597d9c2df7aac2db510bd58dbb107727b2e77f0efbf87056075db5e3b31R74

fix: update S3 integration specs to keep up with changing AWS SDK client shape

---

spec/honeycomb/integrations/sinatra_spec.rb

- [Sinatra 4.1.0 introduced a host authorization option to Sinatra apps](https://github.com/sinatra/sinatra/pull/2053). That authorization check was failing requests made in tests.
-  Update the test Sinatra server to allow anybody to talk to it.

fix: resolve test failures caused by new Sinatra behavior
